sudo: required
dist: trusty

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - echo $PYTHONPATH
  
script:
  - make lint
  - make docs
  - make test
